### ISSUE TITLE
Hub Ready app

### ISSUE THREAD

**Issue by kellyhutchins** [Esri/configurable-app-examples-4x-js#12]
Unless its user error on my part (and it could be) it looks like the hub app is missing some styles. Here's what I see when I run the app: 
![screen shot 2017-11-13 at 11 21 16 am](https://user-images.githubusercontent.com/2124187/32744638-0cdd4762-c865-11e7-8be7-8b8141777b99.png)

fyi @jgravois

**Comment by jgravois** [comment]
agreed. the complete lack of .css is hideous. i'll try and find time for design soon.

**Comment by driskull** [comment]
@kellyhutchins will you verify it's to your liking

**Comment by kellyhutchins** [comment]
Just checked it out and it looks great. Thanks @jgravois.

**Comment by kellyhutchins** [comment]
@jgravois  one super minor thing - jshint is complaining about mixed double and single quotes in the js files. If you get a chance can you update? If not I'll update next time I work on these samples.

**Comment by jgravois** [comment]
no worries. addressed in #17 (and tried adding a new script to lint `*.js` files to assist others)
