### ISSUE TITLE
Loading icon not disappearing (webmap-ts)

### ISSUE THREAD

**Issue by Dadeerh** [Esri/configurable-app-examples-4x-js#27]
When the map is done loading, the loading icon is still active in the background.
This is visible with certain basemaps, or if the basemap is dragged down (see image). 

![image](https://user-images.githubusercontent.com/21084363/57375631-35080400-719e-11e9-9b63-57ff6feb96ce.png)

Let me know if I can supply any further information to help with this.

**Comment by kellyhutchins** [comment]
Installed an update to remove loading icon
