### ISSUE TITLE
Test NPM version of this

### ISSUE THREAD

**Issue by driskull** [Esri/configurable-app-examples-4x-js#9]
Hey @kellyhutchins and @nicksenger can you take a look at the NPM version of this and test it out?

@nicksenger can you think of improvements in the naming/namespace? etc?

**Comment by jgravois** [comment]
forgive me if i'm being dense, but i don't see an [npm package](https://www.npmjs.com/package/configurable-app-examples-4x-js) for this yet.

are you suggesting some kind of [`npm-pack`](https://docs.npmjs.com/cli/pack) type of workflow to ensure that all is well _before_ you publish the samples?

**Comment by driskull** [comment]
The `application-base` is an NPM package that we are using in this repo now. That's all I was meaning :)

**Comment by jgravois** [comment]
gotcha! i for sure used npm to lay `application-base` down and it worked great.

yay for `@esri` scoped packages!

**Comment by driskull** [comment]
YES!

**Comment by kellyhutchins** [comment]
Works great - I'm gonna close this one.
